version: 2
updates:
  # Production dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"
    reviewers:
      - "HasutoSasaki"
    assignees:
      - "HasutoSasaki"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    groups:
      development-dependencies:
        dependency-type: "development"
        exclude-patterns:
          - "@types/*"
          - "eslint*"
          - "typescript"
          - "tailwindcss"
      types-dependencies:
        patterns:
          - "@types/*"
      linting-dependencies:
        patterns:
          - "eslint*"
          - "prettier*"
      # Tailwind CSS関連をグループ化
      tailwind-dependencies:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
    ignore:
      # メジャーバージョンアップは慎重に手動で管理
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "tailwindcss"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@tailwindcss/postcss"
        update-types: ["version-update:semver-major"]
      # React関連は現在v19を使用しているのでメジャーアップデートのみ除外
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/react-dom"
        update-types: ["version-update:semver-major"]

  # GitHub Actionsの依存関係も管理
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "ci"
    labels:
      - "github-actions"
      - "ci"
